### ISSUE TITLE
1.8.9 Mod Port

### ISSUE THREAD

**Issue by shedaniel** [TeNNoX-Mods/CustomSelectionBox#6]
Hi,
    I loved your mod, but it didn't support 1.8.9. So I went and port it into 1.8.9. May I publish it as Custom Selection Box Reloaded or you can update it on your website?

Thanks,
Daniel She

**Comment by tennox** [comment]
Thank you! 

Submit a pull request, and I'll do the rest next week ;)

**Comment by shedaniel** [comment]
Umm I really don't know how to submit a pull request, but this is the file.

This port can be used from 1.8.8 to 1.8.9.
[CustomSelectionBox_1.8.8-1.8.9.zip](https://github.com/TeNNoX-Mods/CustomSelectionBox/files/1608794/CustomSelectionBox_1.8.8-1.8.9.zip)

**Comment by shedaniel** [comment]
I think 1.9 has a lot of changes and I really don't understand the forge of 1.9 or above. So I was unable to port it above 1.8.9. Sorry for that.

**Comment by tennox** [comment]
I need the source files to do anything useful with it.
The compiled jar doesn't help me.

**Comment by shedaniel** [comment]
Ok the source files is here:
[CustomSelectionBoc_1.8.8-1.8.9_sources.zip](https://github.com/TeNNoX-Mods/CustomSelectionBox/files/1617782/CustomSelectionBoc_1.8.8-1.8.9_sources.zip)

**Comment by shedaniel** [comment]
[sources.zip](https://github.com/TeNNoX-Mods/CustomSelectionBox/files/1617784/sources.zip)

**Comment by shedaniel** [comment]
Umm... can you check out the pull request?
https://github.com/TeNNoX-Mods/CustomSelectionBox/pull/7

**Comment by shedaniel** [comment]
Ugh.... How can I contact you?

**Comment by tennox** [comment]
Thank you!
I *might* be able to check it out this weekend.
